{{- range $cur := .Values.configMaps -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "base.metadata" $ | indent 2 }}
  {{- if $cur.name }}
  name: {{ $cur.name | quote }}
  {{- end }}
data:
{{ toYaml . | indent 2 }}
---
{{ end }}
