{{- range $cur := .Values.persistence -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- include "base.metadata" $ | nindent 2 }}
  {{- if $cur.name }}
  name: "{{ $cur.name }}"
  {{- end }}
spec:
  accessModes:
    - {{ $cur.accessMode | quote }}
  resources:
    requests:
      storage: {{ $cur.size | quote }}
{{- if $cur.storageClassName }}
{{- if (eq "-" $cur.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $cur.storageClassName }}"
{{- end }}
{{- end }}
---
{{- end -}}
