{{- range $cur := .Values.persistence -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  {{- include "base.metadata" $ | nindent 2 }}
spec:
  accessModes:
    - {{ $cur.accessMode | quote }}
  capacity:
    storage: {{ $cur.size | quote }}
{{- if $cur.storageClassName }}
{{- if (eq "-" $cur.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $cur.storageClassName }}"
{{- end }}
{{- end }}
{{- if $cur.reclaimPolicy }}
  persistentVolumeReclaimPolicy: "{{ $cur.reclaimPolicy }}"
{{- end }}
{{- if $cur.hostPath }}
  hostPath:
    path: "{{ $cur.hostPath }}"
{{- end }}
{{- if $cur.localPath }}
  local:
    path: "{{ $cur.localPath }}"
{{- end }}
{{- if $cur.nodeSelector }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ $cur.nodeSelector }}
{{- end }}
{{- end }}
