{{- if and .Values.persistence.enabled (not .Values.persistence.existingVolume) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  {{- include "base.metadata" $ | nindent 2 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClassName }}
{{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.hostPath }}
  hostPath:
    path: "{{ .Values.persistence.hostPath }}"
{{- end }}
{{- end }}
