{{- range $cur := .Values.services -}}
apiVersion: v1
kind: Service
metadata:
  {{- include "base.metadata" $ | indent 2 }}
  {{- if $cur.name }}
  name: {{ $cur.name | quote }}
  {{- end }}
spec:
  type: {{ $cur.type }}
  selector:
    {{- include "base.selectorlabels" $ | nindent 4 }}
  ports:
    {{- toYaml $cur.ports | nindent 4 }}
---
{{- end -}}
